# This workflow will install Python dependencies and run the tests with several python versions

name: sphinxcontrib-drawio test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install .
    - name: Install drawio
      run: |
        wget -O drawio.deb https://github.com/jgraph/drawio-desktop/releases/download/v12.6.5/draw.io-amd64-12.6.5.deb
        sudo apt install libasound2 xvfb ./drawio.deb
    - name: Run tests
      run: |
        python -m pytest -vv
